# Generated by Django 5.1.6 on 2025-03-06 14:51

import car_rental.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='booking',
            options={'default_related_name': 'bookings', 'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='review',
            options={'default_related_name': 'reviews'},
        ),
        migrations.AddField(
            model_name='booking',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='carimage',
            name='image_url',
            field=models.ImageField(upload_to=car_rental.models.rename_file),
        ),
    ]
