# Generated by Django 5.1.6 on 2025-03-08 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0003_user_username'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
