# Generated by Django 5.1.6 on 2025-03-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0004_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
