# Generated by Django 5.1.6 on 2025-03-09 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car_rental', '0007_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='car_type',
            field=models.CharField(db_index=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='price_per_day',
            field=models.DecimalField(db_index=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='car',
            name='seat_capacity',
            field=models.IntegerField(db_index=True),
        ),
    ]
